---
title: "Circular Kernel Analysis with Diel Hypotheses"
author: "Brian D. Gerber"
date: "2023-05-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
#Load package
library(Diel.Niche)

#Define year variable
diel.data$min_year = year(as.POSIXct(diel.data$min_date, format = "%m/%d/%Y"))

#Extract winter data in 2019
winter=subset(diel.data, season=="Winter" & min_year=="2019")

#Data visual
head(winter)

#Unique species detected
unique(winter$scientificName)

```

NEXT


```{r setup}
y=cbind(winter$twilight,winter$day, winter$night)
rownames(y)=winter$Common_name
y
```

```{r Analysis}

multi.fit.fun = function(y){
    out = diel.fit(t(as.matrix(y)),hyp.set=hyp.sets("Traditional"),
                 post.fit = FALSE, n.chains = 1,
                 n.mcmc=5000,burnin = 1000, prints=FALSE)

  list(ms.model=out$ms.model,prob=out$bf.table)
}

out.multi=apply(y,1,multi.fit.fun)

#The most supported hypothesis for each species
ms.hyps=unlist(lapply(out.multi,'[',1))

#The probability set for each species
temp=sapply(out.multi,function(x) x[2])
sp.model.probs=matrix(unlist(lapply(temp, "[", , 'Posterior')),
                      ncol=4,byrow = TRUE)
rownames(sp.model.probs)=rownames(y)
colnames(sp.model.probs)=rownames(temp[[1]])


#The probabilities of the most supported hypothesis
prob.hyps=unlist(lapply(lapply(out.multi,'[',2), FUN=function(x){max(x$prob[,2])}))

```